spring:
  application:
    name: Hunters-League

#  datasource:
#    url: jdbc:postgresql://localhost:5432/hunter
#    username: hunter
#    password:
#    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  liquibase:

    change-log: db/changelog/master.yaml
  docker:
    compose:
      file: src/main/docker/compose.yml
      enabled: true
      lifecycle-management: start_only

#server:
#  ssl:
#    enabled: true
#    key-store: classpath:mykeystore.p12
#    key-store-type: PKCS12
#    key-store-password: mypassword
#  #      protocol: TLS
#  #      ciphers: TLS_AES_128_GCM_SHA256, TLS_AES_256_GCM_SHA384, TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
#  #        # Enforce TLS version 1.2 or 1.3 (depending on what the client supports)
#  #      supported-protocols: TLSv1.2, TLSv1.3
#
#  port: 8443